#!/usr/bin/env bash
# JetLag Appliance Setup Script
# Run as root on Ubuntu Server 22.04+
set -euo pipefail

echo "========================================="
echo "  JetLag Appliance Setup"
echo "========================================="

# --- Configuration ---
CONFIG_DIR="/etc/jetlag"
SSL_DIR="${CONFIG_DIR}/ssl"
LOG_DIR="/var/log/jetlag"
DATA_DIR="/var/lib/jetlag"
CAPTURES_DIR="${DATA_DIR}/captures"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"

# --- Check root ---
if [[ $EUID -ne 0 ]]; then
   echo "ERROR: This script must be run as root (sudo)."
   exit 1
fi

# --- Install dependencies ---
echo "[1/8] Installing system packages..."
apt-get update -qq
apt-get install -y -qq \
    dnsmasq \
    nftables \
    iproute2 \
    tcpdump \
    openssl \
    python3 \
    python3-pip \
    python3-venv \
    nodejs \
    npm \
    curl

# --- Create directories ---
echo "[2/8] Creating directories..."
mkdir -p "$CONFIG_DIR" "$SSL_DIR" "$LOG_DIR" "$DATA_DIR" "$CAPTURES_DIR"

# --- Copy config ---
echo "[3/8] Copying configuration..."
if [[ ! -f "${CONFIG_DIR}/jetlag.yaml" ]]; then
    cp "${PROJECT_DIR}/config/jetlag.yaml" "${CONFIG_DIR}/jetlag.yaml"
    echo "  Default config installed to ${CONFIG_DIR}/jetlag.yaml"
else
    echo "  Config already exists, skipping."
fi

# --- Generate self-signed SSL certificate ---
echo "[4/8] Generating self-signed SSL certificate..."
if [[ ! -f "${SSL_DIR}/portal.crt" ]]; then
    openssl req -x509 -nodes -days 3650 \
        -newkey rsa:2048 \
        -keyout "${SSL_DIR}/portal.key" \
        -out "${SSL_DIR}/portal.crt" \
        -subj "/CN=wifi.airline.com/O=SkyConnect Airlines/C=US" \
        2>/dev/null
    echo "  SSL cert generated: ${SSL_DIR}/portal.crt"
else
    echo "  SSL cert already exists, skipping."
fi

# --- Enable IP forwarding ---
echo "[5/8] Enabling IP forwarding..."
sysctl -w net.ipv4.ip_forward=1 > /dev/null
if ! grep -q "net.ipv4.ip_forward=1" /etc/sysctl.conf; then
    echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
fi

# --- Configure dnsmasq ---
echo "[6/8] Configuring dnsmasq..."
# Disable systemd-resolved if it conflicts on port 53
if systemctl is-active --quiet systemd-resolved; then
    echo "  Disabling systemd-resolved (conflicts with dnsmasq on port 53)..."
    systemctl stop systemd-resolved
    systemctl disable systemd-resolved
    # Point resolv.conf to upstream
    rm -f /etc/resolv.conf
    echo "nameserver 1.1.1.1" > /etc/resolv.conf
    echo "nameserver 8.8.8.8" >> /etc/resolv.conf
fi

# dnsmasq config will be generated by the backend on startup
echo "  dnsmasq will be configured by JetLag backend on first start."

# --- Enable nftables ---
echo "[7/8] Enabling nftables..."
systemctl enable nftables
systemctl start nftables || true
echo "  nftables enabled. Firewall rules will be applied by JetLag backend."

# --- Setup Python backend ---
echo "[8/8] Setting up Python backend..."
cd "${PROJECT_DIR}/backend"
if [[ ! -d "venv" ]]; then
    python3 -m venv venv
fi
source venv/bin/activate
pip install -q -r requirements.txt
deactivate

echo ""
echo "========================================="
echo "  Setup complete!"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. Edit /etc/jetlag/jetlag.yaml to match your network interfaces"
echo "  2. Start the backend:"
echo "     cd ${PROJECT_DIR}/backend"
echo "     source venv/bin/activate"
echo "     uvicorn app.main:app --host 0.0.0.0 --port 8080"
echo ""
echo "  3. (Optional) Build and serve the frontend:"
echo "     cd ${PROJECT_DIR}/frontend"
echo "     npm install && npm run build"
echo ""
echo "  4. Access the admin UI at http://<appliance-ip>:8080"
echo "  5. Captive portal will be served on ports 80/443"
echo ""
